/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as TerminBuchenRouteImport } from './routes/termin-buchen'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AnimechsRouteImport } from './routes/animechs'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaecherIndexRouteImport } from './routes/faecher.index'
import { Route as FaecherSubjectRouteImport } from './routes/faecher.$subject'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminBuchenRoute = TerminBuchenRouteImport.update({
  id: '/termin-buchen',
  path: '/termin-buchen',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimechsRoute = AnimechsRouteImport.update({
  id: '/animechs',
  path: '/animechs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaecherIndexRoute = FaecherIndexRouteImport.update({
  id: '/faecher/',
  path: '/faecher/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaecherSubjectRoute = FaecherSubjectRouteImport.update({
  id: '/faecher/$subject',
  path: '/faecher/$subject',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/animechs': typeof AnimechsRoute
  '/apps': typeof AppsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/termin-buchen': typeof TerminBuchenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/faecher/$subject': typeof FaecherSubjectRoute
  '/faecher/': typeof FaecherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/animechs': typeof AnimechsRoute
  '/apps': typeof AppsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/termin-buchen': typeof TerminBuchenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/faecher/$subject': typeof FaecherSubjectRoute
  '/faecher': typeof FaecherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/animechs': typeof AnimechsRoute
  '/apps': typeof AppsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/termin-buchen': typeof TerminBuchenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/faecher/$subject': typeof FaecherSubjectRoute
  '/faecher/': typeof FaecherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/animechs'
    | '/apps'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/termin-buchen'
    | '/ueber-uns'
    | '/faecher/$subject'
    | '/faecher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/animechs'
    | '/apps'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/termin-buchen'
    | '/ueber-uns'
    | '/faecher/$subject'
    | '/faecher'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/animechs'
    | '/apps'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/termin-buchen'
    | '/ueber-uns'
    | '/faecher/$subject'
    | '/faecher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  AnimechsRoute: typeof AnimechsRoute
  AppsRoute: typeof AppsRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PreiseRoute: typeof PreiseRoute
  TerminBuchenRoute: typeof TerminBuchenRoute
  UeberUnsRoute: typeof UeberUnsRoute
  FaecherSubjectRoute: typeof FaecherSubjectRoute
  FaecherIndexRoute: typeof FaecherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termin-buchen': {
      id: '/termin-buchen'
      path: '/termin-buchen'
      fullPath: '/termin-buchen'
      preLoaderRoute: typeof TerminBuchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animechs': {
      id: '/animechs'
      path: '/animechs'
      fullPath: '/animechs'
      preLoaderRoute: typeof AnimechsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faecher/': {
      id: '/faecher/'
      path: '/faecher'
      fullPath: '/faecher/'
      preLoaderRoute: typeof FaecherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faecher/$subject': {
      id: '/faecher/$subject'
      path: '/faecher/$subject'
      fullPath: '/faecher/$subject'
      preLoaderRoute: typeof FaecherSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  AnimechsRoute: AnimechsRoute,
  AppsRoute: AppsRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PreiseRoute: PreiseRoute,
  TerminBuchenRoute: TerminBuchenRoute,
  UeberUnsRoute: UeberUnsRoute,
  FaecherSubjectRoute: FaecherSubjectRoute,
  FaecherIndexRoute: FaecherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
