import type { BrandConfig } from "../brand";

export const topnachhilfeBrand: BrandConfig = {
  id: "topnachhilfe",
  name: "TopNachhilfe",
  // TopNachhilfe uses miStudia's legal entity and contact details as its initial basis.
  legalName: "Markus Autsch miStudia Online Nachhilfe",
  domain: "topnachhilfe.com",
  domains: ["topnachhilfe.com", "www.topnachhilfe.com"],
  slogan: "",
  description: "",
  logo: { src: "", alt: "TopNachhilfe Logo" },
  favicon: "/favicon.ico",
  colors: {
    primary: "oklch(0.58 0.16 240)",
    primaryForeground: "oklch(0.99 0 0)",
    primaryGlow: "oklch(0.72 0.14 220)",
    secondary: "oklch(0.72 0.14 165)",
    secondaryForeground: "oklch(0.18 0.04 240)",
    accentWarm: "oklch(0.78 0.14 55)",
    accent: "oklch(0.95 0.03 200)",
    accentForeground: "oklch(0.28 0.06 240)",
    background: "oklch(0.995 0.005 220)",
    foreground: "oklch(0.22 0.04 250)",
    muted: "oklch(0.96 0.01 230)",
    mutedForeground: "oklch(0.5 0.03 250)",
    card: "oklch(1 0 0)",
    cardForeground: "oklch(0.22 0.04 250)",
    border: "oklch(0.92 0.015 230)",
    input: "oklch(0.94 0.015 230)",
    ring: "oklch(0.58 0.16 240)",
  },
  phone: "+34 625 307 641",
  email: "info@mistudia.de",
  whatsapp: "",
  socialMedia: {
    instagram: "",
    facebook: "",
    linkedin: "",
    youtube: "",
    tiktok: "",
  },
  address: {
    street: "C/ Marqués de Ovieco 6, 6°E",
    postalCode: "29011",
    city: "Málaga",
    country: "Spanien",
    label: "C/ Marqués de Ovieco 6, 6°E, 29011 Málaga, Spanien",
  },
  imprint: {
    providerName: "Markus Autsch miStudia Online Nachhilfe",
    responsiblePerson: "Markus Autsch",
    disclaimer: "",
  },
  privacy: {
    controller:
      "Markus Autsch miStudia Online Nachhilfe, C/ Marqués de Ovieco 6, 6°E, 29011 Málaga, Spanien.",
    contactEmail: "info@mistudia.de",
  },
  seo: {
    title: "",
    description: "",
    canonicalUrl: "",
    ogImage: "",
    twitterHandle: "",
  },
};
